---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      # - PASSWORD=qwe123 #optional
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD=qwe123 #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /Users/crong/Git/deuxksy/container-code-server/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped